сделал первое задание и очень этому рад
Artork/learn-homework-1 pull request #1
Opened 2020-09-09 02:03 UTC by Artork

2020-09-09 02:03 UTC, Artork commented
Надеюсь правильно натыкал))

2020-09-09 11:48 UTC, dolfinus approved these changes
Код рабочий, отступы правильны. Есть пара совсем мелких замечаний, можешь их поправить, добавив еще один коммит с изменениями, но в целом задание выполнено.

2020-09-09 11:48 UTC, dolfinus commented on 1_if1.py
> +      elif user_age >3 and  user_age <=7:
Здесь и ниже у тебя происходит что-то непонятное с пробелами между операторами сравнения:
`user_age <= 7`
vs
`user_age <=7`

Это не ошибка, код будет выполняться, просто читать его не так приятно. Рекомендую сделать везде одинаково.

2020-09-09 11:48 UTC, dolfinus commented on 1_if1.py
> +      elif user_age >3 and  user_age <=7:
Кстати в python можно объединять операторы сравнения. Вместо:
`user_age > 3 and user_age <= 7`
 писать
`3 < useg_age <= 7`

2020-09-09 11:48 UTC, dolfinus commented on 2_if2.py
> +      elif str1 != str2 and str2 == 'learn':
Можно убрать `str1 != str2`, ты ведь уже не попал в блок равенства двух строк, условие и так будет выполнено.

2020-09-09 12:18 UTC, dolfinus commented
Так, посмотрел заново, и нашел ошибку вот здесь:
https://github.com/Artork/learn-homework-1/blob/b4d1dfe32e2f39cc928bcfeccd098562fb2e7485/2_if2.py#L24

У тебя присутствуют два выражения и оператор `and` между ними.
Второе `type(str2) == str` проверит тип переменной str2.
Но первое `type(str1)` просто вернет класс str, а не проверит класс переменной на равенство нужному. При применении оператора `and` результат автоматически будет приведен к типу `bool`, а `bool(любой класс) == True`.
Проверка всегда возвращает `True` для первой переменной, поэтому туда можно случайно передать, например, число, и будет выведен неожиданный результат.

Нужно исправить проверку.

2020-09-10 09:24 UTC, dolfinus requested changes

2020-09-10 09:24 UTC, dolfinus commented on 3_for.py
> +    for i in range(len(scool_10)):
На самом деле индекс тут не нужен. Можно итерироваться сразу по элементам массива:
```python
for item in scool_10:
  scores = sum(item['scores])
```

2020-09-10 09:24 UTC, dolfinus commented on 3_for.py
> +    for i in range(len(scool_10)):
Кстати, можно выполнить все в одном цикле.
На каждом шаге выводить среднюю оценку в классе, а после цикла вывести среднюю оценку по всей школе.

2020-09-10 09:24 UTC, dolfinus commented on 3_for.py
> +    print('Средняя оценка в школе: ', sum_scores/sum_pupol)
Рекомендую применить `round` к среднему значению. Средняя оценка `4.333333` выглядит как-то странно, лучше `4.3` или `4.33`.

2020-09-10 09:25 UTC, dolfinus commented
Добавил замечания по 3 заданию. Жду правки для первых двух и остальные задачи по ДЗ.

2020-09-10 10:41 UTC, dolfinus commented on 3_for.py
> +
Как-то много отступов, лишние стоит убрать.

2020-09-10 15:44 UTC, dolfinus requested changes

2020-09-10 15:44 UTC, dolfinus commented on 1_if1.py
> +      elif 0 <= useg_age <= 7:
В названии переменной опечатка, `useR` vs `useG`

2020-09-10 15:44 UTC, dolfinus commented on 4_while1.py
> +while True:
Цикл вне функции получился, проверь отступы.

2020-09-15 12:23 UTC, dolfinus requested changes

2020-09-15 12:23 UTC, dolfinus commented on 8_ephem_bot.py
> +  planet = user_text.split()[1]
Возможно вместо ручного разбора введенного текста стоит воспользоваться `context.args` - аргументы, переданные команде.

2020-09-15 12:23 UTC, dolfinus commented on 8_ephem_bot.py
> +  from_planet_dict = planet_dict[planetlow]
Ты приводишь планету к lowercase, а потом ищешь еще по ключу в `planet_dict`, вот только там планеты записаны с заглавной буквой.
Нужно либо изменить ключи в dict, либо вместо `.lower()` применять `.title()`.

2020-09-15 12:23 UTC, dolfinus commented on 8_ephem_bot.py
> +  constallation = ephem.constellation(planet1)
Для отладки стоит добавить сюда print и смотреть, отработал ли код. Либо запускать в IDE и использовать breakpoint

2020-09-16 08:28 UTC, dolfinus commented on 6_exception1.py
> +ask_dict = {
Тут тоже что-то не так с отступами.

2020-09-16 08:28 UTC, dolfinus commented on 5_while2.py
> +ask_dict = {
Тут тоже что-то не так с отступами.

2020-09-16 08:29 UTC, dolfinus approved these changes
В целом хорошо, за исключением пары мелких замечаний.

2020-09-17 09:50 UTC, Artork commented on 2_if2.py
> +      elif str1 != str2 and str2 == 'learn':
Скорректировал

2020-09-17 09:50 UTC, Artork commented on 3_for.py
> +    for i in range(len(scool_10)):
Заменил

2020-09-17 09:50 UTC, Artork commented on 3_for.py
> +    for i in range(len(scool_10)):
Код оптимизирован

2020-09-17 09:50 UTC, Artork commented on 3_for.py
> +    print('Средняя оценка в школе: ', sum_scores/sum_pupol)
выполнено

2020-09-17 09:50 UTC, Artork commented on 3_for.py
> +
Убрал

2020-09-17 09:50 UTC, Artork commented on 1_if1.py
> +      elif 0 <= useg_age <= 7:
Исправил

2020-09-17 09:50 UTC, Artork commented on 4_while1.py
> +while True:
Исправил

2020-09-17 09:51 UTC, merged